### ISSUE TITLE
Cuda device not working

### ISSUE THREAD

**Issue by shivamcv** [jesterKing/CCSycles#44] opened 2015-01-21 07:45 UTC
when I select device.cudafirst, it gives following error:
 ILLEGAL_ADDRESS in cuMemAlloc(&device_pointer, size)
 CUDA error: ILLEGAL_ADDRESS in cuCtxSynchronize()

Its working with device.default, and device.cudafirst is working with jan 9 update and not working with update after that (#40 submodule  update).

**Comment by jesterKing** [comment] 2015-01-21 09:54
What kind of device do you have there? I have a GT 420 and GTX 760 on two different machines that get recognised correctly.

Is this with csycles_tester or in your own code?

**Comment by shivamcv** [comment] 2015-01-21 10:06
I am using GT 730 and testing using csycles_tester project, same project is
working with update before #40

On Wed, Jan 21, 2015 at 3:24 PM, Nathan Letwory <notifications@github.com>
wrote:

> What kind of device do you have there? I have a GT 420 and GTX 760 on two
> different machines that get recognised correctly.
>
> Is this with csycles_tester or in your own code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jesterKing/CCSycles/issues/44#issuecomment-70810916>.
>



-- 
Regards

Shivam Singh

Skype id: Shivam.cv
Cell: +919408882207

**Comment by jesterKing** [comment] 2015-01-21 10:47
After searching for a bit I found a very similar error: https://developer.blender.org/T42964

Based on that it looks like you're running out of device memory.

**Comment by shivamcv** [comment] 2015-01-21 10:57
I am not rendering any complex scene, rendering only a single cube from
samples you have provided, and how come its working with older version ?

On Wed, Jan 21, 2015 at 4:17 PM, Nathan Letwory <notifications@github.com>
wrote:

> After searching for a bit I found a very similar error:
> https://developer.blender.org/T42964
>
> Based on that it looks like you're running out of device memory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jesterKing/CCSycles/issues/44#issuecomment-70817511>.
>



-- 
Regards

Shivam Singh

Skype id: Shivam.cv
Cell: +919408882207

**Comment by jesterKing** [comment] 2015-01-21 11:37
That is indeed a weird situation. I am not able to reproduce the error on two different machines.

Perhaps it is an issue with your driver? You could trying to upgrade or if that doesn't work, maybe even downgrade to see if it works any better.

There aren't really any changes to the CUDA initialisation code since then, it is the same as far as I can tell.

**Comment by shivamcv** [comment] 2015-01-22 08:59
sorry, it was my mistake, project dependencies were not set properly, so it was not updating ccycles.dll,

**Comment by jesterKing** [comment] 2015-01-22 09:06
Phew! Thanks for finding and fixing your issue!. Closing :)

**Closed by jesterKing** 2015-01-22 09:06 UTC
